language: generic
env:
  global:
    - IDE_VERSION=1.8.2
  matrix:
    - BOARD="arduino:avr:uno"
    - BOARD="arduino:avr:micro"
    - BOARD="arduino:avr:mega:cpu=atmega2560"
    - BOARD="arduino:samd:arduino_zero_edbg"
    - BOARD="arduino:samd:mkr1000"
    - BOARD="arduino:samd:mkrzero"
before_install:
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide
  - if [[ "$BOARD" =~ "arduino:samd:" ]]; then
      arduino --install-boards arduino:samd &> /dev/null;
    fi
  - buildExampleSketch() { arduino --verbose-build --verify --board $BOARD $PWD/examples/$1/$1.ino; }
install:
  - arduino --install-library "Electronic Cats Internal Temperature Zero Library"
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/Arduino_LoRaWAN_by_Beelan
script:
  - buildExampleSketch lorawan-send-class-A
  - if [[ "$BOARD" == "arduino:samd:arduino_zero_edbg" ]] || [[ "$BOARD" == "arduino:samd:mkr1000" ]] || [[ "$BOARD" == "arduino:samd:mkrzero" ]]; then
      buildExampleSketch lorawan-send-class-A;
    fi
  - buildExampleSketch lorawan-send-class-C